# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dfe0a2de63805ed3109c18cc980d441257224fdfefca6061b0453806312a579d4b88154af41ddac6f259a9c9bb1cbf31f83d21c4daae265d72b5bf48e531d9c

test:
  secret_key_base: 3e573a2aa6ab8c42028aa4a7dbc536ddf57deec4dfb90b0b409020c79dc9dec518e041e7250680be3325d8b2fa0ac46c9a257478c037eac7ec99e832425a1dca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
